export const LAYOUT = {
    INIT: 'LAYOUT_INIT',
    SPLIT_PANEL: 'SPLIT_PANEL',
    MERGE_PANEL: 'MERGE_PANEL'
}

export const UI = {
    TOOL_SELECTED: 'TOOL_SELECTED',
    RESIZE_BEGIN: 'RESIZE_BEGIN',
    RESIZE_DONE : 'RESIZE_DONE',
    MERGE_START: 'MERGE_START'
}