export const MOUSE = {
    LEFT_BUTTON_PRESSED : 'MOUSE_LEFT_BUTTON_PRESSED',
    LEFT_BUTTON_RELEASED: 'MOUSE_LEFT_BUTTON_RELEASED',
    MOVED               : 'MOUSE_MOVED',
}

export const LAYOUT = {
    INIT: 'LAYOUT_INIT',
    SPLIT_PANEL: 'SPLIT_PANEL',
    MERGE_PANEL: 'MERGE_PANEL'
}

export const RESIZE = {
    BEGIN: 'RESIZE_BEGIN',
    DONE : 'RESIZE_DONE'
}

export const UI = {
    TOOL_SELECTED: 'TOOL_SELECTED',
    SPLIT: {
        HORIZONTAL: 'SPLIT_HORIZONTAL',
        VERTICAL: 'SPLIT_VERTICAL'
    },
    MERGE: {
        HORIZONTAL: 'MERGE_HORIZONTAL',
        VERTICAL: 'MERGE_VERTICAL'
    }
}

export const SELECTION = {
    CHANGED: 'CHANGED_SELECTION'
}