export const MOUSE = {
  LEFT_BUTTON_PRESSED: 'MOUSE_LEFT_BUTTON_PRESSED',
  LEFT_BUTTON_RELEASED: 'MOUSE_LEFT_BUTTON_RELEASED',
}

export const REGISTER = {
  CONTAINER: 'CONTAINER_REGISTERED',
  PANEL: 'PANEL_REGISTERED'
}
