export const MOUSE = {
  LEFT_BUTTON_PRESSED : 'MOUSE_LEFT_BUTTON_PRESSED',
  LEFT_BUTTON_RELEASED: 'MOUSE_LEFT_BUTTON_RELEASED',
  MOVED               : 'MOUSE_MOVED',
}

export const REGISTER = {
  CONTAINER: 'CONTAINER_REGISTERED',
  PANEL    : 'PANEL_REGISTERED'
}

export const RESIZE = {
  BEGIN: 'RESIZE_BEGIN',
  DONE : 'RESIZE_DONE'
}
